apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: muha22301/demo-app:jma-2.0   # Gantilah dengan tag image yang sesuai
        ports:
        - containerPort: 8080  # Gantilah jika aplikasi Anda menggunakan port yang berbeda
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Gantilah jika aplikasi Anda menggunakan port yang berbeda
  type: LoadBalancer  # Atau gunakan NodePort jika ingin akses lewat IP Node
