pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                    echo "Testing the application..."
            }
        }

        stage('Build') {
            steps {
                    echo "Building the application..."
            }
        }

        stage('Deploy') {
            steps {
                    echo "Deploying the application..."
            }
        }    
    }
}
